---
- name: Remove Default Host Entry
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1\s+k8s.*$'
    state: absent
  tags:
    - k8s

- name: Ensure Hosts File
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
  with_items:
    - { ip: "192.168.1.10", name: "k8s1" }
    - { ip: "192.168.1.20", name: "k8s2" }
    - { ip: "192.168.1.30", name: "k8s3" }
  tags:
    - k8s

- name: Ensure Docker Apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - k8s

- name: Ensure Docker Repository
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present
    update_cache: yes
  tags:
    - k8s

- name: Ensure Google Cloud Apt Key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - k8s

- name: Ensure Kubernetes Repository
  become: yes
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    update_cache: yes
  tags:
    - k8s

- name: Ensure Base Tools
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - jq
    - bc
    - gawk
    - apt-transport-https
  tags:
    - k8s

- name: Update system
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - k8s

- name: Ensure Docker
  become: yes
  apt:
    name: docker-ce=17.12.1~ce-0~ubuntu
  tags:
    - k8s

- name: Ensure kubelet
  become: yes
  apt:
    name: kubelet=1.11.2-00
  tags:
    - k8s

- name: Ensure kubeadm
  become: yes
  apt:
    name: kubeadm=1.11.2-00
  tags:
    - k8s

- name: Ensure Docker Group
  group:
    name: docker
    state: present
  tags:
    - k8s

- name: Ensure User in Docker Group
  user:
    name=vagrant
    groups=docker
    append=yes
  tags:
    - k8s

- name: Ensure Kubernetes Cleanup
  become:
  copy:
    src: files/clean-k8s
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  tags:
    - k8s

- name: Ensure Docker Socat
  become:
  copy:
    src: files/docker-socat
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  tags:
    - k8s

- name: Ensure swap is off
  become: yes
  command: "swapoff -a"
  tags:
    - k8s

- name: Remove swap from fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: 'swap'
    state: absent
  tags:
    - k8s
