# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 192.168.1.11:30000/nextbreakpoint/flink
  tag: 1.7.2
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: 100m
   memory: 1100Mi
  requests:
   cpu: 100m
   memory: 1100Mi

environment:
  jvmFlags: "-Xms1024M -Xmx1024M"

storage:
  create: false

nodes:
  - "1"
  - "2"
  - "3"
