# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 192.168.1.11:30000/confluentinc/cp-kafka
  tag: 5.0.1
  pullPolicy: IfNotPresent

service:
  firstExternalBrokerPort: 32000
  firstExternalMetricsPort: 32070

resources:
  limits:
   cpu: 100m
   memory: 1100Mi
  requests:
   cpu: 100m
   memory: 1100Mi

environment:
  jvmFlags: "-Xms1024M -Xmx1024M"

secrets:
  password: "test"

nodes:
  - "1"
  - "2"
  - "3"

zookeeper:
  name: zookeeper-headless
  app: zookeeper
  port: 2181
